name: Deploy to ECS

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  deploy:
    uses: ./.github/workflows/ghcr-workflow.yaml
    with:
      aws-region: ${{ secrets.AWS_REGION || 'us-east-2' }}
      ecr-repository-uri: ${{ secrets.ECR_REPOSITORY_URI }}
      container-name: ${{ secrets.CONTAINER_NAME }}
      ecs-service: ${{ secrets.ECS_SERVICE }}
      ecs-cluster: ${{ secrets.ECS_CLUSTER }}
      task-definition-path: './task-definition.json'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}