name: Deploy to ECS

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  deploy:
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: ./.github/workflows/ecs-deploy-reusable.yaml
    with:
      aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}
      ecr-repository-uri: ${{ vars.ECR_REPOSITORY_URI }}
      container-name: ${{ vars.CONTAINER_NAME }}
      ecs-service: ${{ vars.ECS_SERVICE }}
      ecs-cluster: ${{ vars.ECS_CLUSTER }}
      task-definition-path: './task-definition.json'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}