name: Build and Deploy to ECS

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.build-image.outputs.image-uri }}
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker image
      id: build-image
      run: |
        IMAGE_URI=${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        echo "image-uri=$IMAGE_URI" >> $GITHUB_OUTPUT
        
    - name: Create image URI file
      run: echo "${{ steps.build-image.outputs.image-uri }}" > image-uri.txt
      
    - name: Upload image URI
      uses: actions/upload-artifact@v4
      with:
        name: image-uri
        path: image-uri.txt

  security:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    
    steps:
    - name: Download image URI
      uses: actions/download-artifact@v4
      with:
        name: image-uri
        
    - name: Set image URI
      id: image
      run: echo "uri=${{ needs.build.outputs.image-uri }}" >> $GITHUB_OUTPUT
      
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Pull Docker image for scanning
      run: docker pull ${{ steps.image.outputs.uri }}
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.image.outputs.uri }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true

  deploy:
    needs: [build, security]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION || 'us-east-2' }}

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ./task-definition.json
        container-name: ${{ vars.CONTAINER_NAME }}
        image: ${{ needs.build.outputs.image-uri }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ vars.ECS_SERVICE }}
        cluster: ${{ vars.ECS_CLUSTER }}
        wait-for-service-stability: true

  notify:
    needs: [build, security, deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Debug Slack Webhook
      run: |
        if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
          echo "Slack webhook URL is set"
        else
          echo "Slack webhook URL is not set"
        fi
        
    - name: Set deployment status and color
      id: status
      run: |
        if [[ "${{ needs.build.result }}" == "success" && "${{ needs.security.result }}" == "success" && "${{ needs.deploy.result }}" == "success" ]]; then
          echo "status=✅ SUCCESS" >> $GITHUB_OUTPUT
          echo "color=#36a64f" >> $GITHUB_OUTPUT
        elif [[ "${{ needs.build.result }}" == "failure" || "${{ needs.security.result }}" == "failure" || "${{ needs.deploy.result }}" == "failure" ]]; then
          echo "status=❌ FAILURE" >> $GITHUB_OUTPUT
          echo "color=#ff0000" >> $GITHUB_OUTPUT
        else
          echo "status=⏳ PENDING" >> $GITHUB_OUTPUT
          echo "color=#ffff00" >> $GITHUB_OUTPUT
        fi
        
    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            "channel": "#deployments",
            "username": "ECS Deploy Bot",
            "icon_emoji": ":rocket:",
            "attachments": [
              {
                "color": "${{ steps.status.outputs.color }}",
                "title": "ECS Deployment ${{ steps.status.outputs.status }}",
                "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Branch",
                    "value": "${{ github.ref_name }}",
                    "short": true
                  },
                  {
                    "title": "Commit",
                    "value": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                    "short": true
                  },
                  {
                    "title": "Triggered by",
                    "value": "${{ github.actor }}",
                    "short": true
                  },
                  {
                    "title": "Build Status",
                    "value": "${{ needs.build.result == 'success' && '✅' || '❌' }} ${{ needs.build.result }}",
                    "short": true
                  },
                  {
                    "title": "Security Scan",
                    "value": "${{ needs.security.result == 'success' && '✅' || '❌' }} ${{ needs.security.result }}",
                    "short": true
                  },
                  {
                    "title": "Deployment",
                    "value": "${{ needs.deploy.result == 'success' && '✅' || '❌' }} ${{ needs.deploy.result }}",
                    "short": true
                  },
                  {
                    "title": "ECS Service",
                    "value": "${{ vars.ECS_SERVICE }}",
                    "short": true
                  },
                  {
                    "title": "ECS Cluster",
                    "value": "${{ vars.ECS_CLUSTER }}",
                    "short": true
                  },
                  {
                    "title": "AWS Region",
                    "value": "${{ vars.AWS_REGION || 'us-east-2' }}",
                    "short": true
                  },
                  {
                    "title": "Docker Image",
                    "value": "${{ needs.build.outputs.image-uri }}",
                    "short": false
                  }
                ],
                "footer": "GitHub Actions",
                "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                "ts": ${{ github.event.head_commit.timestamp || github.run_id }}
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: env.SLACK_WEBHOOK_URL != ''
      